eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/

server:
  port: 8922

spring:
  application:
    name: xdd-boss-client-provider

  instance:
    prefer-ip-address: true
