eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/

server:
  port: 8921

spring:
  application:
    name: xdd-boss-client-provider

instance:
  prefer-ip-address: true
