eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/

spring:
  application:
    name: client-provider

instance:
  prefer-ip-address: true
