#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8900/eureka/

#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
#spring:
#  application:
#    name: client-provider
#
#instance:
#  prefer-ip-address: true
#server:
#  port: 8761
